name = "site-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

# 定时任务配置 - 每8小时执行一次（0点、8点、16点）
[triggers]
crons = ["0 0,8,16 * * *"]

# KV 存储配置
[[kv_namespaces]]
binding = "SITEMAP_STORAGE"
id = "6f07d2f1f21a4f189366818e4804c838"
preview_id = "f973d10fa9404fe292aa7ee97919d433"

# 环境变量
[vars]
NODE_ENV = "production"

# 生产环境配置
[env.production]
name = "site-bot-prod"

# 开发环境配置
[env.staging]
name = "site-bot-staging" 